server:
  port: 9090
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb?useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver 
    
  jpa: 
    database: mysql
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      
       
  
   
